### ISSUE TITLE
Error - Must inherit from class 'connectionDetails', but has classes 'ConnectionDetails

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/ResultModelManager#17]
To reproduce - use DatabaseConnector 6.0 and ResultsDataModelManager e.g. as called by CohortDiagnostics::createMergedResultsFile

The stack trace looks like this:Stack trace:

> 13: (function (condition) 
> {
>     if (is(condition, "error")) {
>         log("FATAL", conditionMessage(conditio
> 12: stop(simpleError(sprintf(msg, ...), call.))
> 11: mstop("Assertion on '%s' failed: %s.", var.name, res, call. = sys.call(-2))
> 10: makeAssertion(x, res, .var.name, add)
> 9: checkmate::assertClass(connectionDetails, "connectionDetails")
> 8: initialize(...)
> 7: ConnectionHandler$new(connectionDetails, loadConnection = FALSE)
> 6: initialize(...)
> 5: ResultModelManager::DataMigrationManager$new(connectionDetails = connectionDetails, databaseSchema = d
> 4: getDataMigrator(connectionDetails = connectionDetails, databaseSchema = databaseSchema, tablePrefix = 
> 3: migrateDataModel(connectionDetails = connectionDetails, databaseSchema = databaseSchema, tablePrefix =
> 2: createResultsDataModel(connectionDetails = connectionDetails, databaseSchema = "main", tablePrefix = t
> 1: CohortDiagnostics::createMergedResultsFile(dataFolder = folder, overwrite = TRUE, sqliteDbPath = file.

@chrisknoll fyi

**Comment by schuemie** [comment]
Note that this is fixed in the [PR that is being ignored](https://github.com/OHDSI/ResultModelManager/pull/16)
