### ISSUE TITLE
Cannot use createResultsDataModel with sqlite

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/ResultModelManager#21]
If sqlite is supported, then it appears that 'createResultsDataModel' function wont work on it because when running on sqlite 
error is observed referencing the absence of 'information_schema.schemata'

https://github.com/OHDSI/ResultModelManager/blob/cb066fcd44393b4608a3cfa6a8f46d14b20a9daa/R/DataModel.R#L255

**Comment by azimov** [comment]
This function was added in error from OhdsiSharing where it was living in branch for a while - just use `DatabaseConnector::executeSql` - the function will be removed in the next released (and has been removed from develop)
