### ISSUE TITLE
Do we really need createResultsDataModel()?

### ISSUE THREAD

**Issue by schuemie** [OHDSI/ResultModelManager#22]
The `createResultsDataModel()` is just a wrapper around `DatabaseConnector::executeSql()` that first checks if the schema exists using Postgres-specific code so it can throw an R-generated error. If the user were to use `DatabaseConnector::executeSql()` instead, the server would actually already throw an error saying the schema doesn't exist, so I don't understand what this function adds. 

The most reliable part is one that doesn't exist, so I suggest removing this function.

**Comment by azimov** [comment]
This code made it in from the OHDSI sharing branch it came from by mistake, it has been removed in develop and will be taken out in the next release.
