### ISSUE TITLE
Add ability to update evidence synthesis results

### ISSUE THREAD

**Issue by schuemie** [OHDSI/ResultModelManager#30]
I currently don't seem to be able to update evidence synthesis results. If I use `purgeSiteDataBeforeUploading = FALSE`, `uploadResults()` will not upload the new results because old results exist. If I use `purgeSiteDataBeforeUploading = TRUE` it requires a CDM source information CSV file that doesn't make sense in the context of evidence synthesis.

(My current workaround is to delete the 'es_' tables and create them anew, which doesn't seem like a nice solution)

**Comment by azimov** [comment]
Of course - I think I understand your issue -  there will be no database_id in the context of the evidence synthesis data model (which is what the function currently relies on to purge a given site's data).

In this context I think it would be best to implement a "purgeAllData" parameter that will simply call `DELETE FROM` or `TRUNCATE` on all tables in the model spec. This shouldn't take too long to implement.
