### ISSUE TITLE
`connectionString` not honored when passing connection details

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/ResultModelManager#42]
When attempting to establish a pooled connection using `connectionDetails` that specify a `connectionString` and not a `server`, the following code block fails:

https://github.com/OHDSI/ResultModelManager/blob/c1be23c5aa26508acb6b7f9d826aef285871db3e/R/PooledConnectionHandler.R#L46-L53

Perhaps the easiest path here is to validate that the `connectionDetails` object has all of these attributes set when the constructor is called?

**Comment by azimov** [comment]
Though not resolved directly, the develop and hotfix version should allow calling pool directly.

**Comment by azimov** [comment]
I have removed the use of RPostgres as it was not being used and prevented this issue from being fixed, this is resolved in develop and will make its way into the next release
