### ISSUE TITLE
Column `optional` not found in `.data` when using `runCheckAndFixCommands = TRUE`

### ISSUE THREAD

**Issue by schuemie** [OHDSI/ResultModelManager#47]
Not all specifications have an 'optional' column (e.g. [CohortGeneratorModule](https://github.com/OHDSI/CohortGeneratorModule/blob/main/resultsDataModelSpecification.csv)). It would be nice if the upload still worked if it wasn't there.

**Comment by azimov** [comment]
This has been added to the develop branch
