### ISSUE TITLE
Main branch DESCRIPTION file is broken

### ISSUE THREAD

**Issue by egillax** [OHDSI/ResultModelManager#51]
Currently installation of the package using remotes fails

>remotes::install_github('ohdsi/ResultModelManager')
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo ohdsi/ResultModelManager@HEAD
Error: Failed to install 'ResultModelManager' from GitHub:
  Line starting ') ...' is malformed!

This is because of indentation issue, 

```
Authors@R: c(
    person("Jamie", "Gilbert", , "gilbert@ohdsi.org", role = c("aut", "cre"))
) 
```

should be 

```
Authors@R: c(
    person("Jamie", "Gilbert", , "gilbert@ohdsi.org", role = c("aut", "cre"))
    ) 
```

Currently this is breaking CI for all reverse dependencies of the package.

**Comment by azimov** [comment]
Apologies, this was committed by mistake and  should now be resolved
