### ISSUE TITLE
Data type mismatch when using `uploadResults` and `purgeSiteDataBeforeUploading = FALSE`

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/ResultModelManager#52]
Scenario: You've uploaded data that you'd like to preserve when calling the `uploadResults` feature so you specify `purgeSiteDataBeforeUploading = FALSE`. Internally, the `uploadResults` function will read the existing data from the target database and also read the new data for that table from the corresponding .csv file. In some cases, this can result in a data type mismatch since the readr package will infer a data type from the .csv file that does not match the data type that will be used in the database. This results in an error like this:

```r
! Can't join `x$database_id` with `y$database_id` due to incompatible types.
i `x$database_id` is a <character>.
i `y$database_id` is a <double>.
```

From my experience, this is most often that the database table may use a 'character' representation for a given column while the data.frame produced by readr will treat that same column as a numeric. We'd like to make sure that the data being uploaded is using the same data types as dictated by the database to avoid these types of data.

**Comment by azimov** [comment]
Resolved by associated PR
