### ISSUE TITLE
One call to upload all Strategus results?

### ISSUE THREAD

**Issue by schuemie** [OHDSI/ResultModelManager#55]
Currently, if I want to upload results of a Strategus study to a database, I have to write quite a bit of code. Since this is a recurring task, could we add a single function that you can point to a Strategus results folder and will upload everything for you?

**Comment by azimov** [comment]
This seems like it should be in Strategus, Its not clear to me how this package would know what files are where. However, Strategus has pre-orchestrated the entire results folder set with all table specifications in different subdirectories.

**Comment by azimov** [comment]
Closing as this seems like it will be addressed in Strategus directly:

https://github.com/OHDSI/Strategus/pull/145
