### ISSUE TITLE
Optional is misspelled in DataModel.R

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/ResultModelManager#60]
https://github.com/OHDSI/ResultModelManager/blob/develop/R/DataModel.R#L40-L43

```
    if (!"optional" %in% colnames(tableSpecs)) {
      tableSpecs$otpional <- "no"
    }
```

should be ` tableSpecs$optional <- "no"`

**Comment by azimov** [comment]
This issue is now resolved in the develop branch and will be closed after the next release
